name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
    - name: Execute main function
      run: ./main
    - name: Second function to test
      run: ./mainEx01 mat_a3x4.example mat_b4x3.example
